chore: adjust workflow.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,7 +8,45 @@ on:
   workflow_dispatch:
 
 jobs:
+  pre-test:
+    name: Pre-Test Version Check
+    if: github.event_name == 'push' or github.event_name == 'workflow_dispatch'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install build
+          sudo apt-get -y install jq
+      - name: Update SSL certificates
+        run: |
+          python3 scripts/gen_ssl.py
+      - name: Build package
+        run: |
+          python -m build
+      - name: Download PyPI info for version check
+        run: wget -q -O pypi_version.json https://pypi.org/pypi/PyPtt/json
+      - name: Check for version duplication
+        run: |
+          CURRENT_VERSION=$(cat version.txt)
+          PYPI_VERSION=$(jq -r '.info.version' pypi_version.json)
+          echo "Local version: $CURRENT_VERSION"
+          echo "PyPI version: $PYPI_VERSION"
+          if [[ "$CURRENT_VERSION" == "$PYPI_VERSION"* ]]; then
+            echo "Error: Version $CURRENT_VERSION has a prefix that already exists on PyPI ($PYPI_VERSION). Please update the version in PyPtt/__init__.py"
+            exit 1
+          else
+            echo "Version check passed. $CURRENT_VERSION is a new version."
+          fi
+
   test:
+    needs: [pre-test]
+    if: "always() && (needs.pre-test.result == 'success' || needs.pre-test.result == 'skipped')"
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -38,11 +76,11 @@ jobs:
           tests/test_exceptions.py \
           tests/test_logger.py
 
-  deploy:
+  deploy-pypi:
     needs: test
-    name: Deploy to PyPI and Docker
+    name: Deploy to PyPI
     runs-on: ubuntu-latest
-    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'push' or github.event_name == 'workflow_dispatch'
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python
@@ -59,21 +97,6 @@ jobs:
       - name: Build package
         run: |
           python -m build
-      - name: Download PyPI info for version check
-        run: wget -q -O pypi_version.json https://pypi.org/pypi/PyPtt/json
-      - name: Check for version duplication
-        run: |
-          LOCAL_MAIN_VERSION=$(cat main_version.txt)
-          PYPI_VERSION=$(jq -r '.info.version' pypi_version.json)
-          echo "Local version: $LOCAL_MAIN_VERSION"
-          echo "PyPI version: $PYPI_VERSION"
-          if [ "$LOCAL_MAIN_VERSION" == "$PYPI_VERSION" ]; then
-            echo "Error: Version $LOCAL_MAIN_VERSION already exists on PyPI. Please update the version in PyPtt/__init__.py"
-            exit 1
-          else
-            echo "Version check passed. $LOCAL_MAIN_VERSION is a new version."
-          fi
-
       - name: Publish package to TestPyPI
         if: github.ref != 'refs/heads/master'
         uses: pypa/gh-action-pypi-publish@release/v1
@@ -86,9 +109,31 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           password: ${{ secrets.PYPI_API_TOKEN }}
+
+  deploy-ghcr:
+    needs: test
+    name: Deploy to GHCR
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push' or github.event_name == 'workflow_dispatch'
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install build
+      - name: Update SSL certificates
+        run: |
+          python3 scripts/gen_ssl.py
+      - name: Build package
+        run: |
+          python -m build
       - name: Get package version
         id: get_version
-        run: echo "PYPTT_VERSION=$(cat final_version.txt)" >> $GITHUB_ENV
+        run: echo "PYPTT_VERSION=$(cat version.txt)" >> $GITHUB_ENV
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
